meta_product_name: "KondoKondo"
meta_title: "Give stuff you don't need anymore away in your neigbourhood"
meta_description: "KondoKondo - offer things in your neigbourhood, that you want to get rid off but don't want to throw away!"
meta_image: "og-image.png" # should exist in `app/assets/images/`
